<?php

namespace Database\Seeders;

use App\Models\Document;
use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\Storage;

class DocumentSeeder extends Seeder
{
    public function run(): void
    {
        Storage::disk('public')->makeDirectory('documents');

        $dummyContent = "This is a dummy document file for testing purposes.\n\nGenerated by the seeder.";
        
        $documents = [
            [
                'title' => 'Employee Handbook 2026',
                'description' => 'Complete guide to company policies and employee benefits',
                'file_name' => 'employee_handbook.pdf',
                'category_id' => 1,
                'department_id' => 1,
                'uploaded_by' => 2,
                'access_level' => 'public',
            ],
            [
                'title' => 'Code of Conduct',
                'description' => 'Professional behavior guidelines for all employees',
                'file_name' => 'code_of_conduct.pdf',
                'category_id' => 1,
                'department_id' => 1,
                'uploaded_by' => 2,
                'access_level' => 'public',
            ],
            [
                'title' => 'Q1 2026 Financial Report',
                'description' => 'Quarterly financial performance and analysis',
                'file_name' => 'q1_2026_financial_report.xlsx',
                'category_id' => 2,
                'department_id' => 2,
                'uploaded_by' => 3,
                'access_level' => 'department',
            ],
            [
                'title' => 'Budget Allocation 2026',
                'description' => 'Annual budget distribution across departments',
                'file_name' => 'budget_allocation_2026.xlsx',
                'category_id' => 2,
                'department_id' => 2,
                'uploaded_by' => 3,
                'access_level' => 'private',
            ],
            [
                'title' => 'IT Security Policy',
                'description' => 'Information security guidelines and best practices',
                'file_name' => 'it_security_policy.pdf',
                'category_id' => 1,
                'department_id' => 3,
                'uploaded_by' => 4,
                'access_level' => 'public',
            ],
            [
                'title' => 'Software Development Guidelines',
                'description' => 'Coding standards and development workflows',
                'file_name' => 'dev_guidelines.pdf',
                'category_id' => 4,
                'department_id' => 3,
                'uploaded_by' => 4,
                'access_level' => 'department',
            ],
            [
                'title' => 'Network Infrastructure Plan',
                'description' => 'Internal network architecture documentation',
                'file_name' => 'network_plan.docx',
                'category_id' => 2,
                'department_id' => 3,
                'uploaded_by' => 4,
                'access_level' => 'private',
            ],
            [
                'title' => 'Marketing Strategy 2026',
                'description' => 'Annual marketing plan and campaign strategies',
                'file_name' => 'marketing_strategy.pptx',
                'category_id' => 2,
                'department_id' => 4,
                'uploaded_by' => 5,
                'access_level' => 'department',
            ],
            [
                'title' => 'Brand Guidelines',
                'description' => 'Official brand identity and usage guidelines',
                'file_name' => 'brand_guidelines.pdf',
                'category_id' => 4,
                'department_id' => 4,
                'uploaded_by' => 5,
                'access_level' => 'public',
            ],
            [
                'title' => 'Social Media Content Calendar',
                'description' => 'Planned social media posts for Q1 2026',
                'file_name' => 'social_media_calendar.xlsx',
                'category_id' => 3,
                'department_id' => 4,
                'uploaded_by' => 5,
                'access_level' => 'department',
            ],
            [
                'title' => 'Operations Manual',
                'description' => 'Standard operating procedures for daily operations',
                'file_name' => 'operations_manual.pdf',
                'category_id' => 4,
                'department_id' => 5,
                'uploaded_by' => 1,
                'access_level' => 'public',
            ],
            [
                'title' => 'Leave Request Form',
                'description' => 'Template for requesting time off',
                'file_name' => 'leave_request_form.docx',
                'category_id' => 5,
                'department_id' => 1,
                'uploaded_by' => 2,
                'access_level' => 'public',
            ],
            [
                'title' => 'Expense Reimbursement Form',
                'description' => 'Template for submitting expense claims',
                'file_name' => 'expense_form.xlsx',
                'category_id' => 5,
                'department_id' => 2,
                'uploaded_by' => 3,
                'access_level' => 'public',
            ],
            [
                'title' => 'IT Support Request Template',
                'description' => 'Form for submitting technical support tickets',
                'file_name' => 'it_support_template.docx',
                'category_id' => 5,
                'department_id' => 3,
                'uploaded_by' => 4,
                'access_level' => 'public',
            ],
            [
                'title' => 'Meeting Minutes Template',
                'description' => 'Standard template for documenting meeting notes',
                'file_name' => 'meeting_minutes.docx',
                'category_id' => 3,
                'department_id' => 1,
                'uploaded_by' => 2,
                'access_level' => 'public',
            ],
            [
                'title' => 'Performance Review Template',
                'description' => 'Annual employee performance evaluation form',
                'file_name' => 'performance_review.pdf',
                'category_id' => 3,
                'department_id' => 1,
                'uploaded_by' => 2,
                'access_level' => 'department',
            ],
            [
                'title' => 'Onboarding Checklist',
                'description' => 'New employee onboarding tasks and timeline',
                'file_name' => 'onboarding_checklist.pdf',
                'category_id' => 4,
                'department_id' => 1,
                'uploaded_by' => 2,
                'access_level' => 'public',
            ],
            [
                'title' => 'Payroll Schedule 2026',
                'description' => 'Monthly payroll processing dates',
                'file_name' => 'payroll_schedule.pdf',
                'category_id' => 2,
                'department_id' => 2,
                'uploaded_by' => 3,
                'access_level' => 'public',
            ],
            [
                'title' => 'Tax Compliance Guide',
                'description' => 'Tax filing requirements and deadlines',
                'file_name' => 'tax_guide.pdf',
                'category_id' => 4,
                'department_id' => 2,
                'uploaded_by' => 3,
                'access_level' => 'department',
            ],
            [
                'title' => 'Server Maintenance Log',
                'description' => 'Monthly server maintenance activities',
                'file_name' => 'server_log.xlsx',
                'category_id' => 6,
                'department_id' => 3,
                'uploaded_by' => 4,
                'access_level' => 'department',
            ],
            [
                'title' => 'Customer Survey Results',
                'description' => 'Q4 2025 customer satisfaction analysis',
                'file_name' => 'survey_results.pdf',
                'category_id' => 2,
                'department_id' => 4,
                'uploaded_by' => 5,
                'access_level' => 'public',
            ],
            [
                'title' => 'Email Newsletter Template',
                'description' => 'HTML template for monthly newsletters',
                'file_name' => 'newsletter_template.docx',
                'category_id' => 3,
                'department_id' => 4,
                'uploaded_by' => 5,
                'access_level' => 'public',
            ],
            [
                'title' => 'Product Launch Checklist',
                'description' => 'Step-by-step guide for launching new products',
                'file_name' => 'launch_checklist.pdf',
                'category_id' => 4,
                'department_id' => 4,
                'uploaded_by' => 5,
                'access_level' => 'department',
            ],
            [
                'title' => 'Inventory Management System Guide',
                'description' => 'User manual for inventory tracking software',
                'file_name' => 'inventory_guide.pdf',
                'category_id' => 4,
                'department_id' => 5,
                'uploaded_by' => 1,
                'access_level' => 'public',
            ],
            [
                'title' => 'Quality Control Standards',
                'description' => 'Product quality inspection criteria',
                'file_name' => 'qc_standards.pdf',
                'category_id' => 1,
                'department_id' => 5,
                'uploaded_by' => 1,
                'access_level' => 'public',
            ],
            [
                'title' => 'Vendor Contract Template',
                'description' => 'Standard agreement for third-party vendors',
                'file_name' => 'vendor_contract.docx',
                'category_id' => 3,
                'department_id' => 5,
                'uploaded_by' => 1,
                'access_level' => 'department',
            ],
            [
                'title' => 'Safety Training Materials',
                'description' => 'Workplace safety guidelines and procedures',
                'file_name' => 'safety_training.pdf',
                'category_id' => 4,
                'department_id' => 1,
                'uploaded_by' => 2,
                'access_level' => 'public',
            ],
            [
                'title' => 'Remote Work Policy',
                'description' => 'Guidelines for working from home',
                'file_name' => 'remote_work_policy.pdf',
                'category_id' => 1,
                'department_id' => 1,
                'uploaded_by' => 2,
                'access_level' => 'public',
            ],
            [
                'title' => 'Annual Report 2025',
                'description' => 'Company performance summary for 2025',
                'file_name' => 'annual_report_2025.pdf',
                'category_id' => 2,
                'department_id' => 2,
                'uploaded_by' => 3,
                'access_level' => 'public',
            ],
            [
                'title' => 'Data Backup Procedures',
                'description' => 'Step-by-step guide for data backup and recovery',
                'file_name' => 'backup_procedures.pdf',
                'category_id' => 4,
                'department_id' => 3,
                'uploaded_by' => 4,
                'access_level' => 'department',
            ],
        ];

        foreach ($documents as $index => $doc) {
            $fileName = time() . '_' . $index . '_' . $doc['file_name'];
            $filePath = 'documents/' . $fileName;
            
            Storage::disk('public')->put($filePath, $dummyContent);
            
            $extension = pathinfo($doc['file_name'], PATHINFO_EXTENSION);
            
            Document::create([
                'title' => $doc['title'],
                'description' => $doc['description'],
                'file_name' => $doc['file_name'],
                'file_path' => $filePath,
                'file_type' => $extension,
                'file_size' => strlen($dummyContent),
                'category_id' => $doc['category_id'],
                'department_id' => $doc['department_id'],
                'uploaded_by' => $doc['uploaded_by'],
                'access_level' => $doc['access_level'],
                'download_count' => rand(0, 50),
            ]);
        }
    }
}
